In [3]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

In [18]:
X = np.array([[1, 1, 1, 1,1,1,1,1,1,1], [2, 2,2,2,2,2,2,2,2,2]]).reshape(10, 2)
y = np.arange(10)

In [19]:
X

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [20]:
y_lag = sliding_window_view(y, 4)


In [23]:
np.concatenate((y_lag, X[3:,]), axis=1)

array([[0, 1, 2, 3, 1, 1],
       [1, 2, 3, 4, 1, 1],
       [2, 3, 4, 5, 2, 2],
       [3, 4, 5, 6, 2, 2],
       [4, 5, 6, 7, 2, 2],
       [5, 6, 7, 8, 2, 2],
       [6, 7, 8, 9, 2, 2]])

In [15]:
y_lag

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [6]:
X[:, :-1]

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [6, 7],
       [7, 8]])